spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cats?serverTimezone=JST
    username: root
    password: makaron
  jpa:
    hibernate:
      ddl-auto: none
