spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ec2-3-231-188-187.compute-1.amazonaws.com:3306/cats?serverTimezone=JST
    username: sakura
    password: sakura1105
  jpa:
    hibernate:
      ddl-auto: none
      
  mail:
    host: smtp.gmail.com
    port: 587
    username: guanlicats@gmail.com
    password: ijliygsiykswlbrv
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
      
  