package cats.entity;

import java.io.Serializable;
import java.sql.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * ユーザーテーブル モデルクラス.
 *
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity
@Table(name="student")
public class StudentTblEntity implements Serializable{

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** STUDENT_ID. */
	@Id
	private Integer studentId;

	private String studentName;

	private String studentSex;

	private Integer hobbyId;

	private String schoolName;

	private String course;

	private Integer grade;

	private Integer age;

	private String birthplace;

	private String selfIntroduction;

	private String password;

	private String imagePass;

	private Integer point;

	private Date lastLog;

	private Integer continuousLogin;




}
