package cats.entity;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * ユーザーテーブル モデルクラス.
 *
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity
@Table(name="user")
public class UserTblEntity implements Serializable{
	
	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** USER_ID. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int studentsId;
	
	private String name;
	
	private String sex;
	
	private String hobby;
	
	private String school;
	
	private String subject;
	
	private int grade;
	
	private int age;
	
	private String birthplace;
	
	private String introduction;
	
	private String password;
	
	
	

}
